version: "3"
services:
  app:
    image: app
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
    - mongo
    ports:
      - 80:80
      - 3000:3000
    environment:
      DB_HOSTS: mongodb://mongo:27017/posts
    command: bash -c "npm install && npm run start"
  mongo:
    image: mongo
    ports:
      - 27017
