version: "3"
services:
  app:
    image: app
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      DB_HOST: mongodb://mongo:27017/posts
    ports:
      - 3000:3000
    depends_on:
      - mongo
    command: bash -c "npm install && npm run start"
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    expose:
      - 27017
